# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeiIM' do

platform :ios, ‘8.0’
pod 'SDWebImage' , '~> 3.8.2’
use_frameworks!
pod 'XMPPFramework', '~> 3.7.0'
pod 'YYKit'
pod 'MJRefresh', '~> 3.1.12'
pod 'MBProgressHUD'
pod 'YTKKeyValueStore'
pod 'AFNetworking', '~> 3.0'
end
